# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evaluacion', models.CharField(max_length=50)),
                ('tipoEvaluacion', models.IntegerField(choices=[(1, b'Solemne'), (2, b'Control'), (3, b'Examen')], default=1)),
                ('descripcion', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pregunta', models.CharField(max_length=50)),
                ('tipo_pregunta', models.IntegerField(choices=[(1, b'Desarrollo'), (2, b'Terminos pareados'), (3, b'Seleccion multiple')], default=1)),
                ('dificultad', models.IntegerField(choices=[(1, b'Bajo (10% - 30%)'), (2, b'Medio (30% - 60%)'), (3, b'Alto (60% - 90%')], default=1)),
                ('pregunta', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/data')),
                ('respuesta', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sec.contenido')),
            ],
        ),
    ]
