# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('ejes', models.IntegerField(choices=[(1, b'Gestion de proyectos'), (2, b'Arquitectura de software'), (3, b'Desarrollo de software'), (4, b'Otro')])),
                ('regimen', models.IntegerField(choices=[(1, b'Diurno'), (2, b'Vespertino'), (3, b'Advance')], default=1)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
