# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0002_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sec.asignatura'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec.contenido'),
        ),
    ]
